management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#resilience4j:
#  retry:
#    instances:
#      save-comments-db-retry:
#        max-attempts: 3
#        wait-duration: 5s
#      get-comments-db-retry:
#        max-attempts: 3
#        wait-duration: 5s
#      save-credential-db-retry:
#        max-attempts: 3
#        wait-duration: 5s
#      get-credential-db-retry:
#        max-attempts: 3
#        wait-duration: 5s